### ISSUE TITLE
WebTVBundle: Titles are too big for mobile versions.

### ISSUE THREAD

**Issue by Alfro** [campusdomar/PuMuKIT#113]
When viewing the Video Portal on a mobile device, the video title on top of the player will be potentially  split in several lines:

![screen_video_title](https://cloud.githubusercontent.com/assets/11334172/14740264/f6090e10-088d-11e6-9002-8e036d2a38ff.png)
This design is not that much practical, since a title will take up more screen space than the video itself, and it is also positioned first.

Making the title font smaller works to an extent, but since we don't limit title size, it can still become an issue.

**My proposal:**
- Moving the title **under** the video.
- Removing the 'breadcrumbs' (at least on the player)

![screen _2](https://cloud.githubusercontent.com/assets/11334172/14740421/279367ae-088f-11e6-8791-ea8645caf7ce.png)

This approach is cleaner, lets the user watch the video and still shows the title.

_Note: Removing the breadcrumbs leaves no contrast between the navbar/header and the content of the page. But we could make it orange!_

**Comment by mreyk** [comment]
My proposal is to keep the breadcrumbs and move the title under the video as you've suggested.

**Comment by Yurujai** [comment]
Solved in version 3.0 new design
