### ISSUE TITLE
Pumukit docker container fails to run

### ISSUE THREAD

**Issue by pabloegpf1** [campusdomar/PuMuKIT#1218]
When I try to run a container with the official PuMuKIT image, the nginx and mongo containers run correctly but pumukit fails with the error: 
 

`docker: Error response from daemon: driver failed programming external connectivity on endpoint trusting_antonelli (356ad689a3d209c33747744362fc845b2a2e624096a7f9163ab9c4cdf9383bb3): Bind for 0.0.0.0:80 failed: port is already allocated.`

**Comment by Alfro** [comment]
@pabloegpf1 from this
`Bind for 0.0.0.0:80 failed: port is already allocated.`
it seems you have already binded port 80, check if there is another docker already running binded to that port, or another application locally listening on it.
