### ISSUE TITLE
Executing job locked

### ISSUE THREAD

**Issue by pdurancastro** [campusdomar/PuMuKIT#1227]
Hi. I try to upload different videos in one series but one of them it's locked in excecuting process and it can't finalize.
How can I fix it? I can't delete the process, I try to assing other priority to other video and delete the locked video but did'nt work.
I add a screenshot of the process. The version of PuMuKit it's 2.3

![Issue](https://user-images.githubusercontent.com/22289714/62529767-8c6e4c80-b83f-11e9-93ad-cfc2e569fdc9.png)

**Comment by rubenrua** [comment]
Could you check the log file `app/logs/dev.log`.

You also can execute the job via CLI to check errors with:

```
php bin/console  pumukit:encoder:job XXXXXX
```

where XXXXXX is the id of your locked job.

**Comment by pdurancastro** [comment]
Solved! Very Thanks
