### ISSUE TITLE
"pumukit:init:example" is not defined

### ISSUE THREAD

**Issue by pdurancastro** [campusdomar/PuMuKIT#1288]
Hi, I'm trying to install PuMuKIT x2.4 for ubuntu 18.04 but in the 18 step (Load example data) I have the next error: 
![pumukitexamplenotdefined](https://user-images.githubusercontent.com/22289714/66295628-11332080-e8ec-11e9-8a62-ed05ecb49ee7.png)
How can i solve it?
Thanks in advance

**Comment by albacodina** [comment]
Hi!
You must add the following line in App_Kernel.php file:
`new Pumukit\ExampleDataBundle\PumukitExampleDataBundle()`

To improve your experience, I recommend that you install the lastest version. You can find it [here](https://github.com/pumukit/PuMuKIT) and its documentation [here](https://github.com/pumukit/PuMuKIT-doc/). You can use Docker in this version.

**Comment by albacodina** [comment]
I explain you how you can should do to install the new version and the bundle you want.

Steps:

1. `git clone git@github.com:pumukit/PuMuKIT.git`
2.  cd PuMuKIT
3. `docker-compose up -d` => With this command you run Pumukit.
4. `docker exec -it pumukit_php_1 sh` => This command opens "the console" in Docker.
5. `composer require teltek/pumukit-example-data-bundle 1.0.x`
6. Add to AppKernel.php => `new Pumukit\ExampleDataBundle\PumukitExampleDataBundle()`
7. Execute this command => `php bin/console pumukit:init:example --force`

**Comment by pdurancastro** [comment]
Thanks I install it successfully. I had to change the port of docker-compose to 8084 and the installation doesn't give me more errors. 
I have one more question, how can I load this example on the front end? 
I can only see the last configuration and the example did not load.
Thanks for the help.

**Comment by albacodina** [comment]
Following the steps above https://github.com/campusdomar/PuMuKIT/issues/1288#issuecomment-539886530, the data-example appears on the front-end.

**Comment by pdurancastro** [comment]
Finally I decided to create my own page but really thanks for the help.
