### ISSUE TITLE
The cancel button reloads the object to its initial state, regardless of the last saved changes

### ISSUE THREAD

**Issue by iriadp** [campusdomar/PuMuKIT#225]
Steps:
- Access to PuMuKIT
- Go to the Media Manager
- Edit a Series or a Multimedia Object
- Save the changes but do not reload the Series/Multimedia Object
- Make another change and instead of saving it, cancel it.

Error:
- The cancel button makes the Series/Multimedia Object show you the initial state instead of the real state (after saving it). You need to reload the Series/Multimedia Object to see its real state

**Comment by Yurujai** [comment]
Solved in version 3.0
