### ISSUE TITLE
It is mandatory to refresh a multimedia object at least once in order to see its multimedia files

### ISSUE THREAD

**Issue by iriadp** [campusdomar/PuMuKIT#235]
Steps:

- Create a Series
- Create a Multimedia Object
- Upload its master
- Go to the publication tab and check WebTV
- Go to the multimedia tab

Error:

It only appears the master. You need to refresh the multimedia object to see the new broadcast file it is being created (or it has already finished)

**Comment by Yurujai** [comment]
Solved in version 3.0
