### ISSUE TITLE
#6532 Backend: Tables: People: New: It does not turn the page when creating more than 10 people  

### ISSUE THREAD

**Issue by bmartinezteltek** [campusdomar/PuMuKIT#25]
It does not turn the page when creating more than 10 people .

**Comment by Alfro** [comment]
Still present on 2.4.x:
*Steps:*
* Create enough people to take more than one page.
* Create a new person, giving it a name that will put it last (people are sorted by name)
*Expected Result:*
* The new person I just created appears on screen.
*Actual Result:*
* The person doesn't seem to have been created. Moving to the next page shows the person was actually created.

**Comment by Yurujai** [comment]
Solved in version 3.0
