### ISSUE TITLE
NewAdminBundle: download track from Multimedia Tab loads URL (plays video) instead of download file

### ISSUE THREAD

**Issue by mreyk** [campusdomar/PuMuKIT#284]
Only happens in Firefox. Tested in 50.x version of Firefox and 2.4.x version of Pumukit.

https://github.com/campusdomar/PuMuKIT2/blob/2.4.x/src/Pumukit/NewAdminBundle/Resources/views/Track/list.html.twig#L87

```
href="{{ path('pumukitnewadmin_track_download', {'id': track.id, 'mmId': mm.id}) }}" download>
```

**Comment by silviabf** [comment]
It is fixed to Firefox 68.0.2 and Pumukit 3.x
