### ISSUE TITLE
There is no error message if you upload a material from url without title

### ISSUE THREAD

**Issue by silviabf** [campusdomar/PuMuKIT#371]
Steps:
- Go to backoffice
- Select any multimedia object and go to multimedia tab.
- Click on upload new material
- Do not write any title
- Select url and write a valid url for a material

Problem: There is an error because the tittle is compulsory, but when you use a url the pop up window is closed without show an error and the material is not uploaded. If you upload a file the error is shown correctly.

**Comment by Yurujai** [comment]
Solved in version 3.0
