### ISSUE TITLE
Using an iframe with only logged users/groups broadcast doesn't allow you to authenticate

### ISSUE THREAD

**Issue by iriadp** [campusdomar/PuMuKIT#372]
Steps:

- Create a MO with broadcast only for logged users or groups.
- Copy the iframe code and add it to a webpage.
- Try to watch the video in the other webpage with another browser.

Error:
The iframe shows you the login webpage in fullscreen inside the iframe space. You can't see the login area therefore you can't authenticate yourself to watch the video.

**Comment by silviabf** [comment]
Fixed in Pumukit 3.x. Now, you can login inside the iframe. The login area appears now with a scrollbar.
