### ISSUE TITLE
Go to the same page of the list where a new event has just been created

### ISSUE THREAD

**Issue by iriadp** [campusdomar/PuMuKIT#391]
Steps to reproduce it:
- Go to the 'Live Events' list.
- Go to a page of the list.
- Create a new event for a previous or future date that the ones listed in this page.

Actual behaviour: The event is created and placed in chronological order but we continue in the same page as we were and probably we cannot see the new event.

Expected behaviour: When the event is created, the webpage should be reloaded and we should watch the page of the list where our new event is.

**Comment by 1M4** [comment]
Trying to fix this issue I've noticed that the same problem occurs when you try to update an Event.

**Comment by Yurujai** [comment]
Solved in version 3.0
