### ISSUE TITLE
Add Open Graph properties in video and series page

### ISSUE THREAD

**Issue by rubenrua** [campusdomar/PuMuKIT#403]
From TTK-13525. 

See http://gethead.info

**Comment by Yurujai** [comment]
Done for MultimediaObject: https://github.com/campusdomar/PuMuKIT/blob/master/src/Pumukit/WebTVBundle/Resources/views/MultimediaObject/template.html.twig#L13-L17

Done for Series:

https://github.com/campusdomar/PuMuKIT/blob/master/src/Pumukit/WebTVBundle/Resources/views/Series/template.html.twig#L8-L12
